import { CaseIcon } from "@sanity/icons/Case";
import { defineField, defineType } from "sanity";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  icon: CaseIcon,
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "media", title: "Media" },
    { name: "meta", title: "Meta" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "content",
      validation: (rule) =>
        rule.required().regex(/^\d{4}$/, { name: "4-digit year" }),
    }),
    defineField({
      name: "role",
      title: "Role",
      description: "What you did on this project, e.g. Design, Frontend Development.",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "tools",
      title: "Tools",
      description: "Tech stack used, e.g. Next.js, GSAP, Figma.",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "info",
      title: "Info",
      description: "Short case description shown on the project page.",
      type: "text",
      rows: 4,
      group: "content",
    }),
    defineField({
      name: "coverImage",
      title: "Cover image",
      description: "Used in the Selected Works list and Achievements thumbnails.",
      type: "image",
      group: "media",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      description: "Large image at the top of the project page.",
      type: "image",
      group: "media",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "media",
      of: [{ type: "galleryItem" }],
    }),
    defineField({
      name: "nextProject",
      title: "Next project",
      description: "Which project to link to from the \"Next project\" section.",
      type: "reference",
      group: "meta",
      to: [{ type: "project" }],
    }),
    defineField({
      name: "liveLink",
      title: "Live link",
      description: "URL to the live site, shown in the project meta as \"Live\".",
      type: "url",
      group: "meta",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "githubLink",
      title: "GitHub link",
      description: "URL to the source repository, shown in the project meta as \"Source\".",
      type: "url",
      group: "meta",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "order",
      title: "Order",
      description: "Controls position in the Selected Works list (lower first).",
      type: "number",
      group: "meta",
      initialValue: 0,
    }),
    defineField({
      name: "isVisible",
      title: "Visible on site",
      description: "Turn off to hide this project from the site without deleting it.",
      type: "boolean",
      group: "meta",
      initialValue: true,
    }),
  ],
  orderings: [
    {
      title: "Display order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      year: "year",
      media: "coverImage",
      isVisible: "isVisible",
    },
    prepare: ({ title, year, media, isVisible }) => ({
      title,
      subtitle: `${year} — ${isVisible === false ? "Hidden" : "Visible"}`,
      media,
    }),
  },
});
